### PR TITLE
adds new nodes to prx.conf from masternodes.online nodes list

### PR DESCRIPTION
**Pull request by bedri**
The script was not able to sync the blockchain with the DNS seeds so I added working addnode lines to the script to echo into prx.conf files of the masternodes.

After this addition the stuck in synchronization problem solved.

Hope this will help a lot others.

@sburns1369 thanks for this script. I liked it ;)

### CODE REVIEW

**Comment by bedri** [comment]
Well it seams i missed to adjust home directory names of the nodes after the first node so don't merge it yet. I will fix them and commit again.

**Comment by bedri** [comment]
Ok committed the corrected files.

**Comment by sburns1369** [comment]
Thanks for the commits, I'll look at the shortly in depth.  I generate all the scripts from a script engine that I wrote; and over the past two weeks I did a massive overhaul on it.  With in the next 48 hours trying to push on a full re-lease after testing and tweaking.  I was originally asked not to advertise them publicly, but the cat is sort of out of the bag, so they will be maintained better. 
    On Thursday, March 21, 2019, 7:39:22 PM EDT, bedri <notifications@github.com> wrote:  
 
 
Well it seams i missed to adjust home directory names of the nodes after the first node so don't merge it yet. I will fix them and commit again.

**Review by sburns1369 — APPROVED** [review]
Thanks. Approving to commend your effort, and for credit.  New script in full will be pushed in about 10 minutes

**Pull request closed without merging**
